#Sun Oct 25 02:19:59 CET 2015
lang=EN
window_width=1080
key_moveleft=29
window_fullscreen=false
key_moveright=32
key_jump=62
window_vsync=false
mastervolume=0.8
window_hdpi_macosx=false
key_moveup=51
key_movedown=47
window_height=720
