#Sat Oct 24 21:48:45 CEST 2015
lang=EN
window_width=1080
key_moveleft=29
window_fullscreen=false
key_moveright=32
window_vsync=false
mastervolume=0.8
window_hdpi_macosx=false
key_moveup=51
key_movedown=47
window_height=720
