#Sat Oct 24 21:38:51 CEST 2015
lang=EN
window_width=1080
key_moveleft=29
window_fullscreen=false
key_moveright=32
window_vsync=false
mastervolume=0.8
window_hdpi_macosx=false
window_height=720
key_movedown=47
key_moveup=51
